---
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
baseurl: "https://blog-george644261.codeanyapp.com/"
builddrafts: false

title: "tuan.pro"
author: "George tuan"
copyright: "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."

canonifyurls: true

params:
  calloutTitle: "the winding road  - development"
